const createUserController = require('@/controllers/middlewaresControllers/createUserController');
const createUser = require('./createUser');
const updateUser = require('./updateUser');
const deleteUser = require('./deleteUser');
const methods = createUserController('Admin');
methods.createUser = createUser;
methods.updateUser = updateUser;
methods.deleteUser = deleteUser;
module.exports = methods;
